- name: Create datomic user.
  user: name=datomic state=present

- name: Create datomic data directory
  file: state=directory path={{ datomic_data_dir }} owner=datomic group=datomic mode=755

- name: Make datomic log directory
  file: state=directory path=/var/log/datomic owner=datomic group=datomic
  
- name: Check datomic installation
  command: ls {{ datomic_dir }}/{{ datomic_filename }}
  register: datomic_exists
  ignore_errors: true

- name: Create datomic directory
  file: state=directory path={{ datomic_dir }} owner=datomic group=datomic
  when: datomic_exists|failed

- name: Download datomic
  get_url: url=https://my.datomic.com/downloads/free/{{ datomic_version }} dest={{ datomic_dir }}/{{ datomic_filename }}
  when: datomic_exists|failed

- name: Unpack datomic
  command: chdir={{ datomic_dir }} unzip {{ datomic_filename }}
  when: datomic_exists|failed

- name: datomic dir permissions
  shell: chown -R datomic:datomic {{ datomic_dir }}/{{ datomic_filename }}

- name: Upload datomic properties file
  copy: src=files/datomic-transactor.properties dest={{ datomic_dir }}/transactor.properties
  notify: restart datomic
  
- name: Upload datomic upstart config file
  copy: src=files/datomic-upstart.conf dest=/etc/init/datomic.conf
  notify: restart datomic
  
- name: Link datomic
  file: src={{ datomic_dir }}/datomic-free-{{ datomic_version }}
        dest={{ datomic_dir }}/runtime
        owner=datomic
        group=datomic
        state=link
  when: datomic_exists|failed
